spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Dealer
    username: root
    password: linda010495-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: dev
environment: dev
server:
  port: 5000

logging.level:
  root: info
  com.develhope.spring.users.services.UserService: info
  com.develhope.spring.users.controllers.RegistrationController: info
  com.develhope.spring.users.controllers: info

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Dealer
    username: root
    password: linda010495-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: prod
environment: prod
server:
  port: 8080

logging.level:
  root: info
  com.develhope.spring.users.services.UserService: info
  com.develhope.spring.users.controllers.RegistrationController: info
  com.develhope.spring.users.controllers: info

---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: test
environment: test
server:
  port: 8080
