spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Dealer
    username: root
    password: linda010495-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

logging.level:
  root: info
  com.develhope.spring.users.services.UserService: info
  com.develhope.spring.users.controllers.RegistrationController: info
  com.develhope.spring.users.controllers: info

