package vehicle.enumerators;

public enum Optionals {
    HEATEDSEATS,
    LEATHERSEATS,
    HEATEDWINDOW,
    ALLOYWHEEL,
    ALLWHEELDRIVE,
    POWERTAILGATE,
    HEATEDSTEERINGWHEEL,
    REARBACKCAMERA,
    PARKINGSENSORS;
}
